routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\SubAdminController;
use App\Models\SubAdmin;

Route::group(['middleware' => ['revalidate']], function () {
	Route::get('/home', function () {
		return redirect(route('admin.dashboard.index'));
	})->name('home');

	// Profile
	Route::get('profile/', 'Admin\PagesController@profile')->name('profile-view');
	Route::post('profile/update', 'Admin\PagesController@updateProfile')->name('profile.update');
	Route::put('change/password', 'Admin\PagesController@updatePassword')->name('update-password');

	// Quick Link
	Route::get('quickLink', 'Admin\PagesController@quickLink')->name('quickLink');
	Route::post('link/update', 'Admin\PagesController@updateQuickLink')->name('update-quickLink');
});


//route for the admin
Route::group(['namespace' => 'Admin', 'middleware' => ['check_permit', 'revalidate']], function () {

	/* Dashboard */
	Route::get('/', 'PagesController@dashboard')->name('dashboard.index');
	Route::get('/dashboard', 'PagesController@dashboard')->name('dashboard.index');

	/* User */
	Route::get('users/listing', 'UsersController@listing')->name('users.listing');
	Route::resource('users', 'UsersController');


	/* Role Management */
	Route::get('roles/listing', 'AdminController@listing')->name('roles.listing');
	Route::resource('roles', 'AdminController');

	/* Country Management*/
	Route::get('countries/listing', 'CountryController@listing')->name('countries.listing');
	Route::resource('countries', 'CountryController');

	/* State Management*/
	Route::get('states/listing', 'StateController@listing')->name('states.listing');
	Route::resource('states', 'StateController');

	/* City Management*/
	Route::get('cities/listing', 'CityController@listing')->name('cities.listing');
	Route::resource('cities', 'CityController');

	/* CMS Management*/
	Route::get('pages/listing', 'CmsPagesController@listing')->name('pages.listing');
	Route::resource('pages', 'CmsPagesController');

	/* Site Configuration */
	Route::get('settings', 'PagesController@showSetting')->name('settings.index');
	Route::post('change-setting', 'PagesController@changeSetting')->name('settings.change-setting');

	//subadmin route
	// admin.subadmin.listing
	Route::get('subadmin/listing', 'SubAdminController@listing')->name('subadmin.listing');
	Route::resource('subadmin', 'SubAdminController');

	//category and sub category 
	Route::get('category/listing', 'CategoryController@listing')->name('category.listing');
	Route::resource('category', 'CategoryController');

	Route::get('ingredients/listing', 'IngredientController@listing')->name('ingredients.listing');
	Route::resource('ingredients', 'IngredientController');

	Route::get('measurement/listing', 'MeasureMentController@listing')->name('measurement.listing');
	Route::resource('measurement', 'MeasureMentController');

	Route::get('quantity/listing', 'QuantityController@listing')->name('quantity.listing');
	Route::resource('quantity', 'QuantityController');

	//recipe 
	Route::post('favorite', 'FavoriteController@favorite')->name('recipe.favorite');
	Route::get('recipe/listing', 'RecipeController@listing')->name('recipe.listing');
	Route::resource('recipe', 'RecipeController');

	//test image upload using the dropzone 
	Route::get('dropzone', 'DropzoneController@index')->name('dropzone');
	Route::post('dropzone', 'DropzoneController@dropzoneFileUpload')->name('dropzoneFileUpload');

	//dropzone image delete 
	Route::post('img-delete', 'DropzoneController@recipeImageDelete')->name('recipeImageDelete');
	//uploaded images 
	Route::get('uploaded_img', 'DropzoneController@fetchDropzoneImage')->name('uploaded_img');


	//like dislike the recipe 
	Route::post('like-dislike', 'LikeDislikeController@likeDislike')->name('recipe.likeDislike');
});



//User Exception
Route::get('users-error-listing', 'Admin\ErrorController@listing')->name('error.listing');
//Chart routes
Route::get('register-users-chart', 'Admin\ChartController@getRegisterUser')->name('users.registerchart');
Route::get('active-deactive-users-chart', 'Admin\ChartController@getActiveDeactiveUser')->name('users.activeDeactiveChart');

Route::post('check-email', 'UtilityController@checkEmail')->name('check.email');
Route::post('check-name', 'UtilityController@checkName')->name('check.name');
Route::post('check-contact', 'UtilityController@checkContact')->name('check.contact');

Route::post('summernote-image-upload', 'Admin\SummernoteController@imageUpload')->name('summernote.imageUpload');
Route::post('summernote-media-image', 'Admin\SummernoteController@mediaDelete')->name('summernote.mediaDelete');

Route::post('check-title', 'UtilityController@checkTitle')->name('check.title');
Route::post('profile/check-password', 'UtilityController@profilecheckpassword')->name('profile.check-password');

routes/web.php
<?php

use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\SubAdmin\Auth\AuthenticateController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('index');
});


Auth::routes(['register' => false, 'login' => false]);

Route::get('login', 'AdminAuth\LoginController@showLoginForm')->name('login');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin'], function () {
  Route::get('login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');
  Route::post('login', 'AdminAuth\LoginController@login');
  Route::get('logout', 'AdminAuth\LoginController@logout')->name('admin.logout');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('admin.password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
  Route::get('/password/reset/{token}/{email?}', 'AdminAuth\ResetPasswordController@showResetForm');
});
Route::post('check-email', 'UtilityController@checkEmail')->name('check.email');
Route::post('check-contact', 'UtilityController@checkContact')->name('check.contact');

//sub-admin routes
Route::group(['prefix' => 'sub-admin','as'=>'sub_admin.'], function () {
  
  //subadmin reset the password
  Route::get('reset-password/{token?}', [AuthenticateController::class, 'showResetPassword'])->name('reset_password_link');
  Route::post('reset-password', [AuthenticateController::class, 'resetPassword'])->name("reset-password");

  //login route 
  Route::get('login', [AuthenticateController::class, 'showLogin'])->name('login');
  Route::post('login', [AuthenticateController::class, 'checkLogin'])->name('checkLogin');
  
  //forgot password
  Route::get('forgot-password', [AuthenticateController::class, 'showForgotPassword'])->name('forgot_password');
  Route::post('send-link', [AuthenticateController::class, 'sendLinkForgotPassword'])->name('send_link');

  //this is the new method to reset the password using password broker 
  // Route::get('/password/reset/{token?}', [AuthenticateController::class, 'showResetForm'])->name('reset_password_form');
  // Route::post('/password/reset', [AuthenticateController::class, 'reset'])->name('reset_password'); 

  //sub admin register 


  //category and sub category crud 
  Route::get('/register', [AuthenticateController::class, 'registration'])->name('registration');
  Route::post('/register', [AuthenticateController::class, 'postRegistration'])->name('registration.post'); 

});

app/Models/Admin/MeasurMent.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MeasurMent extends Model
{
    public function getRouteKeyName()
    {
        return 'custom_id';
    }
    protected $table = "measurment";
    protected $fillable = ['name','custom_id']; 
    use HasFactory;
}

resources/views/admin/pages/measurment/create.blade.php
@extends('admin.layouts.app')

@push('breadcrumb')
    {!! Breadcrumbs::render('measurement_create') !!}
@endpush
@push('extra-css-styles')
    <style>
        strong.form-text {
            color: red !important;
        }
    </style>
@endpush
@section('content')
    <div class="container">
        <div class="card card-custom">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon">
                        <i class="fa fa-thermometer-empty text-primary"></i>
                    </span>
                    <h3 class="card-label text-uppercase">ADD {{ $custom_title }}</h3>
                </div>
            </div>

            <!--begin::Form-->
            <form id="frmMeasureMent" method="POST" action="{{ route('admin.measurement.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                    {{-- First Name --}}
                    <div class="form-group">
                        <label for="name">{!! $mend_sign !!} Name : </label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                            name="name" value="{{ old('name') }}" placeholder="Enter Measurment name"
                            autocomplete="name" spellcheck="false" autocapitalize="sentences" tabindex="0"
                            autofocus />
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong class="form-text">{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary mr-2 text-uppercase"> Add {{ $custom_title }}</button>
                    <a href="{{ route('admin.measurement.index') }}" class="btn btn-secondary text-uppercase">Cancel</a>
                </div>
            </form>
            <!--end::Form-->
        </div>
    </div>
@endsection

@push('extra-js-scripts')
    <script>
        $(document).ready(function() {
            $("#frmMeasureMent").validate({
                rules: {
                    name: {
                        required: true,
                        not_empty: true,
                        minlength: 3,
                    },
                },
                messages: {
                    name: {
                        required: "@lang('validation.required', ['attribute' => 'measurment name'])",
                        not_empty: "@lang('validation.not_empty', ['attribute' => 'measurment name'])",
                        minlength: "@lang('validation.min.string', ['attribute' => 'measurment name', 'min' => 3])",
                    },
                },
                errorClass: 'invalid-feedback',
                errorElement: 'span',
                highlight: function(element) {
                    $(element).addClass('is-invalid');
                    $(element).siblings('label').addClass('text-danger'); // For Label
                },
                unhighlight: function(element) {
                    $(element).removeClass('is-invalid');
                    $(element).siblings('label').removeClass('text-danger'); // For Label
                },
                errorPlacement: function(error, element) {
                    if (element.attr("data-error-container")) {
                        error.appendTo(element.attr("data-error-container"));
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
            $('#frmMeasureMent').submit(function() {
                if ($(this).valid()) {
                    addOverlay();
                    $("input[type=submit], input[type=button], button[type=submit]").prop("disabled",
                        "disabled");
                    return true;
                } else {
                    return false;
                }
            });
        });
    </script>
@endpush

resources/views/admin/pages/measurment/edit.blade.php
@extends('admin.layouts.app')

@push('breadcrumb')
    {!! Breadcrumbs::render('measurement_update', $measurement->id) !!}
@endpush
@push('extra-css-styles')
    <style>
        strong.form-text {
            color: red !important;
        }
    </style>
@endpush
@section('content')
    <div class="container">
        <div class="card card-custom">
            <div class="card-header">
                <div class="card-title">
                    <span class="card-icon">
                        <i class="fa fa-thermometer-empty text-primary"></i>
                    </span>
                    <h3 class="card-label text-uppercase">Edit {{ $custom_title }}</h3>
                </div>
            </div>

            <!--begin::Form-->
            <form id="frmEditMeasurment" method="POST"
                action="{{ route('admin.measurement.update', $measurement->custom_id) }}" enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="card-body">

                    {{-- First Name --}}
                    <div class="form-group">
                        <label for="name">{!! $mend_sign !!} Name:</label>
                        <input type="text" class="form-control @error('name') is-invalid @enderror" id="name"
                            name="name" value="{{ old('name') != null ? old('name') : $measurement->name }}"
                            placeholder="Enter Measurment name" autocomplete="name" spellcheck="false"
                            autocapitalize="sentences" tabindex="0" autofocus />
                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong class="form-text">{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>

                </div>
                <div class="card-footer">
                    <button type="submit" class="btn btn-primary mr-2">Update {{ $custom_title }}</button>
                    <a href="{{ route('admin.measurement.index') }}" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
            <!--end::Form-->
        </div>
    </div>
@endsection

@push('extra-js-scripts')
    <script>
        $(document).ready(function() {
            $("#frmEditMeasurment").validate({
                rules: {
                    name: {
                        required: true,
                        not_empty: true,
                        minlength: 3,
                        only_alpha: true,
                        remote: {
                            url: "{{ route('admin.check.name') }}",
                            type: "post",
                            data: {
                                _token: "{{ csrf_token() }}",
                                type: "measurment",
                                id: " {{ $measurement->id }} ",
                            }
                        },
                    },

                },
                messages: {
                    name: {
                        required: "@lang('validation.required', ['attribute' => 'measurement'])",
                        not_empty: "@lang('validation.not_empty', ['attribute' => 'measurement'])",
                        minlength: "@lang('validation.min.string', ['attribute' => 'measurement', 'min' => 3])",
                        remote: "@lang('validation.unique', ['attribute' => 'measurment'])",
                        only_alpha: "Enter valid measurment name",
                    },

                },
                errorClass: 'invalid-feedback',
                errorElement: 'span',
                highlight: function(element) {
                    $(element).addClass('is-invalid');
                    $(element).siblings('label').addClass('text-danger'); // For Label
                },
                unhighlight: function(element) {
                    $(element).removeClass('is-invalid');
                    $(element).siblings('label').removeClass('text-danger');
                },
                errorPlacement: function(error, element) {
                    if (element.attr("data-error-container")) {
                        error.appendTo(element.attr("data-error-container"));
                    } else {
                        error.insertAfter(element);
                    }
                }
            });
            $('#frmEditMeasurment').submit(function() {
                if ($(this).valid()) {
                    addOverlay();
                    $("input[type=submit], input[type=button], button[type=submit]").prop("disabled",
                        "disabled");
                    return true;
                } else {
                    return false;
                }
            });

        });
    </script>
@endpush

resources/views/admin/pages/measurment/index.blade.php
@extends('admin.layouts.app')

@push('breadcrumb')
    {!! Breadcrumbs::render('measurement') !!}
@endpush

@push('extra-css-styles')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css') }}" />
@endpush

@section('content')
<div class="container">

    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon">
                    <i class="fa fa-thermometer-empty text-primary"></i>
                </span>
                <h3 class="card-label">Measurments</h3>
            </div>

            <div class="card-toolbar">
                @if (in_array('delete', $permissions))
                    <a href="{{ route('admin.measurement.destroy', 0) }}" name="del_select" id="del_select" class="btn btn-sm btn-light-danger font-weight-bolder text-uppercase mr-2 delete_all_link">
                        <i class="far fa-trash-alt"></i> Delete Selected
                    </a>
                @endif
                @if (in_array('add', $permissions))
                    <a href="{{ route('admin.measurement.create') }}" class="btn btn-sm btn-primary font-weight-bolder text-uppercase">
                        <i class="fas fa-plus"></i>
                        Add {{ $custom_title }}
                    </a>
                @endif
            </div>
        </div>
        <div class="card-body">
            {{--  Datatable Start  --}}
            <table class="table table-bordered table-hover table-checkable" id="measurement_tbl" style="margin-top: 13px !important"></table>
            {{--  Datatable End  --}}
        </div>
    </div>
</div>
@endsection

@push('extra-js-scripts')
<script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script>
    $(document).ready(function () {
        // datatable
        oTable = $('#measurement_tbl').DataTable({
            responsive: true,
            searchDelay: 500,
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('admin.measurement.listing') }}",
                data: {
                    columnsDef: ['checkbox','name', 'active', 'action'],
                },
            },
            columns: [
                { data: 'checkbox' },
                { data: 'name' },
                { data: 'active' },
                { data: 'action', responsivePriority: -1 },
            ],
            columnDefs: [
                // Specify columns titles here...
                { targets: 0, title: "<center><input type='checkbox' class='all_select'></center>", orderable: false },
                { targets: 1, title: 'Name', orderable: true },
                { targets: 2, title: 'Active', orderable: false },
                { targets: -1, title: 'Action',
                orderable: false },
            ],
            order: [
                [1, 'asc']
            ],
            lengthMenu: [
                [10, 20, 50, 100],
                [10, 20, 50, 100]
            ],
            pageLength: 10,
        });
    });
</script>
@endpush

resources/views/admin/pages/measurment/trashed.blade.php
@extends('admin.layouts.app')

@push('extra-css-styles')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css') }}" />
@endpush

@section('content')
<div class="container">
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon">
                    <i class="fas fa-users text-primary"></i>
                </span>
                <h3 class="card-label">{{ $custom_title }}</h3>
            </div>
            
            <div class="card-toolbar">
            </div>
        </div>
        <div class="card-body">
            <!--begin: Datatable-->
            <table class="table table-bordered table-hover table-checkable" id="users_table" style="margin-top: 13px !important">
            </table>
            <!--end: Datatable-->
        </div>
    </div>
</div>
@endsection

@push('extra-js-scripts')
<script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script>
    $(document).ready(function () {
        // datatable
        $('#users_table').DataTable({
            responsive: true,
            searchDelay: 500,
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('admin.users.trasheddata') }}",
                data: {
                    columnsDef: ['first_name', 'last_name', 'email', 'contact_no'],
                },
            },
            columns: [
                { data: 'first_name' },
                { data: 'last_name' },
                { data: 'email' },
                { data: 'contact_no' },
            ],
            columnDefs: [
                // Specify columns titles here...
                { targets: 0, title: 'First Name', orderable: true },
                { targets: 1, title: 'Last Name', orderable: true },
                { targets: 2, title: 'Email', orderable: true },
                { targets: 3, title: 'Contact Number', orderable: true }
            ],
            order: [
                [0, 'asc']
            ],
            lengthMenu: [
                [10, 20, 50, 100],
                [10, 20, 50, 100]
            ],
            pageLength: 10,
        });
    });
</script>
@endpush