routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\SubAdminController;
use App\Models\SubAdmin;

Route::group(['middleware' => ['revalidate']], function () {
	Route::get('/home', function () {
		return redirect(route('admin.dashboard.index'));
	})->name('home');

	// Profile
	Route::get('profile/', 'Admin\PagesController@profile')->name('profile-view');
	Route::post('profile/update', 'Admin\PagesController@updateProfile')->name('profile.update');
	Route::put('change/password', 'Admin\PagesController@updatePassword')->name('update-password');

	// Quick Link
	Route::get('quickLink', 'Admin\PagesController@quickLink')->name('quickLink');
	Route::post('link/update', 'Admin\PagesController@updateQuickLink')->name('update-quickLink');
});


//route for the admin
Route::group(['namespace' => 'Admin', 'middleware' => ['check_permit', 'revalidate']], function () {

	/* Dashboard */
	Route::get('/', 'PagesController@dashboard')->name('dashboard.index');
	Route::get('/dashboard', 'PagesController@dashboard')->name('dashboard.index');

	/* User */
	Route::get('users/listing', 'UsersController@listing')->name('users.listing');
	Route::resource('users', 'UsersController');


	/* Role Management */
	Route::get('roles/listing', 'AdminController@listing')->name('roles.listing');
	Route::resource('roles', 'AdminController');

	/* Country Management*/
	Route::get('countries/listing', 'CountryController@listing')->name('countries.listing');
	Route::resource('countries', 'CountryController');

	/* State Management*/
	Route::get('states/listing', 'StateController@listing')->name('states.listing');
	Route::resource('states', 'StateController');

	/* City Management*/
	Route::get('cities/listing', 'CityController@listing')->name('cities.listing');
	Route::resource('cities', 'CityController');

	/* CMS Management*/
	Route::get('pages/listing', 'CmsPagesController@listing')->name('pages.listing');
	Route::resource('pages', 'CmsPagesController');

	/* Site Configuration */
	Route::get('settings', 'PagesController@showSetting')->name('settings.index');
	Route::post('change-setting', 'PagesController@changeSetting')->name('settings.change-setting');

	//subadmin route
	// admin.subadmin.listing
	Route::get('subadmin/listing', 'SubAdminController@listing')->name('subadmin.listing');
	Route::resource('subadmin', 'SubAdminController');

	//category and sub category 
	Route::get('category/listing', 'CategoryController@listing')->name('category.listing');
	Route::resource('category', 'CategoryController');

	Route::get('ingredients/listing', 'IngredientController@listing')->name('ingredients.listing');
	Route::resource('ingredients', 'IngredientController');

	Route::get('measurement/listing', 'MeasureMentController@listing')->name('measurement.listing');
	Route::resource('measurement', 'MeasureMentController');

	Route::get('quantity/listing', 'QuantityController@listing')->name('quantity.listing');
	Route::resource('quantity', 'QuantityController');

	//recipe 
	Route::post('favorite', 'FavoriteController@favorite')->name('recipe.favorite');
	Route::get('recipe/listing', 'RecipeController@listing')->name('recipe.listing');
	Route::resource('recipe', 'RecipeController');

	//test image upload using the dropzone 
	Route::get('dropzone', 'DropzoneController@index')->name('dropzone');
	Route::post('dropzone', 'DropzoneController@dropzoneFileUpload')->name('dropzoneFileUpload');

	//dropzone image delete 
	Route::post('img-delete', 'DropzoneController@recipeImageDelete')->name('recipeImageDelete');
	//uploaded images 
	Route::get('uploaded_img', 'DropzoneController@fetchDropzoneImage')->name('uploaded_img');


	//like dislike the recipe 
	Route::post('like-dislike', 'LikeDislikeController@likeDislike')->name('recipe.likeDislike');
});



//User Exception
Route::get('users-error-listing', 'Admin\ErrorController@listing')->name('error.listing');
//Chart routes
Route::get('register-users-chart', 'Admin\ChartController@getRegisterUser')->name('users.registerchart');
Route::get('active-deactive-users-chart', 'Admin\ChartController@getActiveDeactiveUser')->name('users.activeDeactiveChart');

Route::post('check-email', 'UtilityController@checkEmail')->name('check.email');
Route::post('check-name', 'UtilityController@checkName')->name('check.name');
Route::post('check-contact', 'UtilityController@checkContact')->name('check.contact');

Route::post('summernote-image-upload', 'Admin\SummernoteController@imageUpload')->name('summernote.imageUpload');
Route::post('summernote-media-image', 'Admin\SummernoteController@mediaDelete')->name('summernote.mediaDelete');

Route::post('check-title', 'UtilityController@checkTitle')->name('check.title');
Route::post('profile/check-password', 'UtilityController@profilecheckpassword')->name('profile.check-password');

routes/web.php
<?php

use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\SubAdmin\Auth\AuthenticateController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('index');
});


Auth::routes(['register' => false, 'login' => false]);

Route::get('login', 'AdminAuth\LoginController@showLoginForm')->name('login');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin'], function () {
  Route::get('login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');
  Route::post('login', 'AdminAuth\LoginController@login');
  Route::get('logout', 'AdminAuth\LoginController@logout')->name('admin.logout');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('admin.password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
  Route::get('/password/reset/{token}/{email?}', 'AdminAuth\ResetPasswordController@showResetForm');
});
Route::post('check-email', 'UtilityController@checkEmail')->name('check.email');
Route::post('check-contact', 'UtilityController@checkContact')->name('check.contact');

//sub-admin routes
Route::group(['prefix' => 'sub-admin','as'=>'sub_admin.'], function () {
  
  //subadmin reset the password
  Route::get('reset-password/{token?}', [AuthenticateController::class, 'showResetPassword'])->name('reset_password_link');
  Route::post('reset-password', [AuthenticateController::class, 'resetPassword'])->name("reset-password");

  //login route 
  Route::get('login', [AuthenticateController::class, 'showLogin'])->name('login');
  Route::post('login', [AuthenticateController::class, 'checkLogin'])->name('checkLogin');
  
  //forgot password
  Route::get('forgot-password', [AuthenticateController::class, 'showForgotPassword'])->name('forgot_password');
  Route::post('send-link', [AuthenticateController::class, 'sendLinkForgotPassword'])->name('send_link');

  //this is the new method to reset the password using password broker 
  // Route::get('/password/reset/{token?}', [AuthenticateController::class, 'showResetForm'])->name('reset_password_form');
  // Route::post('/password/reset', [AuthenticateController::class, 'reset'])->name('reset_password'); 

  //sub admin register 


  //category and sub category crud 
  Route::get('/register', [AuthenticateController::class, 'registration'])->name('registration');
  Route::post('/register', [AuthenticateController::class, 'postRegistration'])->name('registration.post'); 

});

resources/views/admin/pages/cms/edit.blade.php
@extends('admin.layouts.app')
@push('breadcrumb')
    {!! Breadcrumbs::render('cms_update', $page->id) !!}
@endpush

@section('content')
<div class="container">
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon">
                    <i class="{{$icon}} text-primary"></i>
                </span>
                <h3 class="card-label text-uppercase">Edit {{ $custom_title }}</h3>
            </div>
        </div>

        <!--begin::Form-->
        <form id="frmEditcms" method="POST" action="{{ route('admin.pages.update', $page->id) }}" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="card-body">

                {{--  Name --}}
                <div class="form-group">
                    <label for="title">Title{!!$mend_sign!!}</label>
                    <input type="text" class="form-control @error('title') is-invalid @enderror" id="title" name="title" value="{{ old('title') != null ? old('title') : $page->title }}" placeholder="Enter title" autocomplete="title" spellcheck="false" autocapitalize="sentences" tabindex="0" autofocus />
                    @if ($errors->has('title'))
                        <span class="help-block">
                            <strong class="form-text">{{ $errors->first('title') }}</strong>
                        </span>
                    @endif
                </div>

                {{-- Description --}}
                <div class="form-group">
                    <label for="description">Description{!!$mend_sign!!}</label>
                    <textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" placeholder="Enter description" autocomplete="description" spellcheck="true">{{ old('description') != null ? old('description') : $page->description }}</textarea>
                    @if ($errors->has('description'))
                        <span class="text-danger">
                            <strong class="form-text">{{ $errors->first('description') }}</strong>
                        </span>
                    @endif
                </div>

                {{-- Image --}}
                <div class="form-group">
                    <label for="image">Image</label>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="image" name="image" tabindex="0" />
                        <label class="custom-file-label @error('image') is-invalid @enderror" for="customFile">Choose file</label>
                        @if ($errors->has('image'))
                            <span class="text-danger">
                                <strong class="form-text">{{ $errors->first('image') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary mr-2">Update {{ $custom_title }}</button>
                <a href="{{ route('admin.pages.index') }}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
        <!--end::Form-->
    </div>
</div>
@endsection

@push('extra-js-scripts')
<script type="text/javascript">
    var summernoteImageUpload = '{{ route('admin.summernote.imageUpload') }}';
    var summernoteMediaDelete = '{{ route('admin.summernote.mediaDelete') }}';
</script>
<script src="{{ asset('admin/plugins/summernote/summernotecustom.js') }}"></script>
<script>
$(document).ready(function () {
    var summernoteElement = $('#description');
    var imagePath = 'summernote/cms/image';
    summernoteElement.summernote({
            height: 300,
            callbacks: {
                onImageUpload : function(files, editor, welEditable) {
                     for(var i = files.length - 1; i >= 0; i--) {
                             sendFile(files[i], this,imagePath);
                    }
                },
                onMediaDelete : function(target) {
                    deleteFile(target[0].src);
                },
            }
    });
    $("#frmEditcms").validate({
        rules: {
            title: {
                required: true,
                not_empty: true,
                minlength: 3,
                remote: {
                    url: "{{ route('admin.check.title') }}",
                    type: "post",
                    data: {
                        _token: "{{csrf_token()}}",
                        id: "{{$page->id}}",
                        type: "cms",
                    }
                },
            },
            url: {
                required: true,
                not_empty: true,
                isurl:true,
            },
            image:{
                required:false,
                extension: "jpg|jpeg|png",
            },
        },
        messages: {
            title: {
                required: "@lang('validation.required',['attribute'=>'title'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'title'])",
                minlength:"@lang('validation.min.string',['attribute'=>'title','min'=>3])",
                remote:"@lang('validation.unique',['attribute'=>'title'])",
            },
            url: {
                required: "@lang('validation.required',['attribute'=>'url'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'url'])",
            },
            image: {
                required: "@lang('validation.required',['attribute'=>'image'])",
                extension:"@lang('validation.mimetypes',['attribute'=>'image','value'=>'jpg|png|jpeg'])",
            },
        },
        errorClass: 'invalid-feedback',
        errorElement: 'span',
        highlight: function (element) {
            $(element).addClass('is-invalid');
            $(element).siblings('label').addClass('text-danger'); // For Label
        },
        unhighlight: function (element) {
            $(element).removeClass('is-invalid');
            $(element).siblings('label').removeClass('text-danger');
        },
        errorPlacement: function (error, element) {
            if (element.attr("data-error-container")) {
                error.appendTo(element.attr("data-error-container"));
            } else {
                error.insertAfter(element);
            }
        }
    });
    $('#frmEditcms').submit(function (e) {
      if(summernoteElement.summernote('isEmpty')) {
        $('#description-error').remove();
        $('<span class="text-danger" id="description-error"><strong class="form-text">The description field is required.</strong></span>').insertAfter('.note-editor');
        e.preventDefault();
        return false;
      }else {
        if ($(this).valid()) {
            addOverlay();
            $("input[type=submit], input[type=button], button[type=submit]").prop("disabled", "disabled");
            return true;
        } else {
            return false;
        }
      }
    });

    //tell the validator to ignore Summernote elements
    $('form').each(function () {
        if ($(this).data('validator'))
            $(this).data('validator').settings.ignore = ".note-editor *";
    });
});
</script>
@endpush

resources/views/admin/pages/cms/index.blade.php
@extends('admin.layouts.app')
@push('breadcrumb')
{!! Breadcrumbs::render('cms_list') !!}
@endpush

@push('extra-css-styles')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css') }}" />
@endpush

@section('content')
<div class="container">

    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon">
                    <i class="{{$icon}} text-primary"></i>
                </span>
                <h3 class="card-label">{{ $custom_title }}</h3>
            </div>
            <div class="card-toolbar">
                @if (in_array('delete', $permissions))
                <a href="{{ route('admin.pages.destroy', 0) }}" name="del_select" id="del_select" class="btn btn-sm btn-light-danger font-weight-bolder text-uppercase mr-2 delete_all_link" data-module="{{strtolower($custom_title)}}" data-route-name="{{ $routeName }}">
                    <i class="far fa-trash-alt"></i> Delete Selected
                </a>
                @endif
                @if (in_array('add', $permissions))
                <a href="{{ route('admin.pages.create') }}" class="btn btn-sm btn-primary font-weight-bolder text-uppercase">
                    <i class="fas fa-plus"></i>
                    Add {{ str_singular($custom_title) }}
                </a>
                @endif
            </div>
        </div>

        <div class="card-body">
        {{-- Datatable Start  --}}
            <table class="table table-bordered table-hover table-checkable" id="pages_DT" style="margin-top: 13px !important"></table>
            {{-- Datatable End  --}}
        </div>
        <!-- End: life time stats -->
    </div>
</div>
@endsection

@push('extra-js-scripts')
<script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script type="text/javascript">
    $(function(){
        var table = $('#pages_DT');

        oTable = table.DataTable({
            responsive: true,
            searchDelay: 500,
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('admin.pages.listing') }}",
                data: {
                    columnsDef: ['','title','description','action'],
                },
            },
            columns: [
                {
                    data: 'checkbox'
                },
                {
                    data: 'title'
                },
                {
                    data: 'description'
                },
                {
                    data: 'action',
                    responsivePriority: -1
                },
            ],
            columnDefs: [
                // Specify columns titles here...
                {
                    targets: 0,
                    title: "<center><input type='checkbox' class='all_select'></center>",
                    orderable: false,
                    visible: false
                },
                {
                    targets: 1,
                    title: 'Page',
                    orderable: true
                },
                {
                    targets: 2,
                    title: 'Description',
                    orderable: false,
                    class: 'none'
                },
                {
                    targets: -1,
                    title: 'Action',
                    orderable: false
                },
            ],
            order: [
                [1, 'asc']
            ],
            lengthMenu: [
                [10, 20, 50, 100],
                [10, 20, 50, 100]
            ],
            pageLength: 10,
        });



    });
</script>
@endpush