routes/admin.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\SubAdminController;
use App\Models\SubAdmin;

Route::group(['middleware' => ['revalidate']], function () {
	Route::get('/home', function () {
		return redirect(route('admin.dashboard.index'));
	})->name('home');

	// Profile
	Route::get('profile/', 'Admin\PagesController@profile')->name('profile-view');
	Route::post('profile/update', 'Admin\PagesController@updateProfile')->name('profile.update');
	Route::put('change/password', 'Admin\PagesController@updatePassword')->name('update-password');

	// Quick Link
	Route::get('quickLink', 'Admin\PagesController@quickLink')->name('quickLink');
	Route::post('link/update', 'Admin\PagesController@updateQuickLink')->name('update-quickLink');
});


//route for the admin
Route::group(['namespace' => 'Admin', 'middleware' => ['check_permit', 'revalidate']], function () {

	/* Dashboard */
	Route::get('/', 'PagesController@dashboard')->name('dashboard.index');
	Route::get('/dashboard', 'PagesController@dashboard')->name('dashboard.index');

	/* User */
	Route::get('users/listing', 'UsersController@listing')->name('users.listing');
	Route::resource('users', 'UsersController');


	/* Role Management */
	Route::get('roles/listing', 'AdminController@listing')->name('roles.listing');
	Route::resource('roles', 'AdminController');

	/* Country Management*/
	Route::get('countries/listing', 'CountryController@listing')->name('countries.listing');
	Route::resource('countries', 'CountryController');

	/* State Management*/
	Route::get('states/listing', 'StateController@listing')->name('states.listing');
	Route::resource('states', 'StateController');

	/* City Management*/
	Route::get('cities/listing', 'CityController@listing')->name('cities.listing');
	Route::resource('cities', 'CityController');

	/* CMS Management*/
	Route::get('pages/listing', 'CmsPagesController@listing')->name('pages.listing');
	Route::resource('pages', 'CmsPagesController');

	/* Site Configuration */
	Route::get('settings', 'PagesController@showSetting')->name('settings.index');
	Route::post('change-setting', 'PagesController@changeSetting')->name('settings.change-setting');

	//subadmin route
	// admin.subadmin.listing
	Route::get('subadmin/listing', 'SubAdminController@listing')->name('subadmin.listing');
	Route::resource('subadmin', 'SubAdminController');

	//category and sub category 
	Route::get('category/listing', 'CategoryController@listing')->name('category.listing');
	Route::resource('category', 'CategoryController');

	Route::get('ingredients/listing', 'IngredientController@listing')->name('ingredients.listing');
	Route::resource('ingredients', 'IngredientController');

	Route::get('measurement/listing', 'MeasureMentController@listing')->name('measurement.listing');
	Route::resource('measurement', 'MeasureMentController');

	Route::get('quantity/listing', 'QuantityController@listing')->name('quantity.listing');
	Route::resource('quantity', 'QuantityController');

	//recipe 
	Route::post('favorite', 'FavoriteController@favorite')->name('recipe.favorite');
	Route::get('recipe/listing', 'RecipeController@listing')->name('recipe.listing');
	Route::resource('recipe', 'RecipeController');

	//test image upload using the dropzone 
	Route::get('dropzone', 'DropzoneController@index')->name('dropzone');
	Route::post('dropzone', 'DropzoneController@dropzoneFileUpload')->name('dropzoneFileUpload');

	//dropzone image delete 
	Route::post('img-delete', 'DropzoneController@recipeImageDelete')->name('recipeImageDelete');
	//uploaded images 
	Route::get('uploaded_img', 'DropzoneController@fetchDropzoneImage')->name('uploaded_img');


	//like dislike the recipe 
	Route::post('like-dislike', 'LikeDislikeController@likeDislike')->name('recipe.likeDislike');
});



//User Exception
Route::get('users-error-listing', 'Admin\ErrorController@listing')->name('error.listing');
//Chart routes
Route::get('register-users-chart', 'Admin\ChartController@getRegisterUser')->name('users.registerchart');
Route::get('active-deactive-users-chart', 'Admin\ChartController@getActiveDeactiveUser')->name('users.activeDeactiveChart');

Route::post('check-email', 'UtilityController@checkEmail')->name('check.email');
Route::post('check-name', 'UtilityController@checkName')->name('check.name');
Route::post('check-contact', 'UtilityController@checkContact')->name('check.contact');

Route::post('summernote-image-upload', 'Admin\SummernoteController@imageUpload')->name('summernote.imageUpload');
Route::post('summernote-media-image', 'Admin\SummernoteController@mediaDelete')->name('summernote.mediaDelete');

Route::post('check-title', 'UtilityController@checkTitle')->name('check.title');
Route::post('profile/check-password', 'UtilityController@profilecheckpassword')->name('profile.check-password');

routes/web.php
<?php

use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\SubAdmin\Auth\AuthenticateController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return view('index');
});


Auth::routes(['register' => false, 'login' => false]);

Route::get('login', 'AdminAuth\LoginController@showLoginForm')->name('login');

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['prefix' => 'admin'], function () {
  Route::get('login', 'AdminAuth\LoginController@showLoginForm')->name('admin.login');
  Route::post('login', 'AdminAuth\LoginController@login');
  Route::get('logout', 'AdminAuth\LoginController@logout')->name('admin.logout');

  Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.request');
  Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('admin.password.email');
  Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('admin.password.reset');
  Route::get('/password/reset/{token}/{email?}', 'AdminAuth\ResetPasswordController@showResetForm');
});
Route::post('check-email', 'UtilityController@checkEmail')->name('check.email');
Route::post('check-contact', 'UtilityController@checkContact')->name('check.contact');

//sub-admin routes
Route::group(['prefix' => 'sub-admin','as'=>'sub_admin.'], function () {
  
  //subadmin reset the password
  Route::get('reset-password/{token?}', [AuthenticateController::class, 'showResetPassword'])->name('reset_password_link');
  Route::post('reset-password', [AuthenticateController::class, 'resetPassword'])->name("reset-password");

  //login route 
  Route::get('login', [AuthenticateController::class, 'showLogin'])->name('login');
  Route::post('login', [AuthenticateController::class, 'checkLogin'])->name('checkLogin');
  
  //forgot password
  Route::get('forgot-password', [AuthenticateController::class, 'showForgotPassword'])->name('forgot_password');
  Route::post('send-link', [AuthenticateController::class, 'sendLinkForgotPassword'])->name('send_link');

  //this is the new method to reset the password using password broker 
  // Route::get('/password/reset/{token?}', [AuthenticateController::class, 'showResetForm'])->name('reset_password_form');
  // Route::post('/password/reset', [AuthenticateController::class, 'reset'])->name('reset_password'); 

  //sub admin register 


  //category and sub category crud 
  Route::get('/register', [AuthenticateController::class, 'registration'])->name('registration');
  Route::post('/register', [AuthenticateController::class, 'postRegistration'])->name('registration.post'); 

});

app/Models/Country.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Country extends Model
{
    protected $fillable = ['code', 'name', 'phonecode'];

    public function states()
    {
        return $this->hasMany('App\Models\State');
    }
}

app/Http/Controllers/Admin/CountryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\CountryRequest;
use App\Models\Country;
use Illuminate\Http\Request;

class CountryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.pages.general.countries.index')->with(['custom_title' => 'Countries']);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.general.countries.create')->with(['custom_title' => 'Country']);
    }

     /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CountryRequest $request)
    {
        $country = Country::create($request->all());
        if ($country) {
            flash('Country created successfully!')->success();
        } else {
            flash('Unable to save country. Please try again later.')->error();
        }
        return redirect(route('admin.countries.index'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Country $country)
    {
        return view('admin.pages.general.countries.edit', compact('country'))->with(['custom_title' => 'Country']);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CountryRequest $request, Country $country)
    {
        if (!empty($request->action) && $request->action == 'change_status') {
            $content = ['status' => 204, 'message' => "something went wrong"];
            if ($country) {
                $country->is_active = $request->value;
                if ($country->save()) {
                    $content['status'] = 200;
                    $content['message'] = "Status updated successfully.";
                }
            }
            return response()->json($content);
        } else {
            $country->fill($request->all());
            if ($country->save()) {
                flash('User details updated successfully!')->success();
            } else {
                flash('Unable to update user. Try again later')->error();
            }
            return redirect(route('admin.countries.index'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {
        if (!empty($request->action) && $request->action == 'delete_all') {
            $content = ['status' => 204, 'message' => "something went wrong"];
            Country::whereIn('id', explode(',', $request->ids))->delete();
            $content['status'] = 200;
            $content['message'] = "Country deleted successfully.";
            $content['count'] = Country::all()->count();
            return response()->json($content);
        } else {
            $country = Country::where('id', $id)->firstOrFail();
            $country->delete();
            if (request()->ajax()) {
                $content = array('status' => 200, 'message' => "Country deleted successfully.", 'count' => Country::all()->count());
                return response()->json($content);
            } else {
                flash('Country deleted successfully.')->success();
                return redirect()->route('admin.countries.index');
            }
        }
    }



    public function listing(Request $request)
    {
        extract($this->DTFilters($request->all()));
        $records = [];
        $countries = Country::orderBy($sort_column, $sort_order);

        if ($search != '') {
            $countries->where(function ($query) use ($search) {
                $query->where('name', 'like', "%{$search}%")
                    ->orWhere('code', 'like', "%{$search}%")
                    ->orWhere('phonecode', 'like', "%{$search}%");
            });
        }

        $count = $countries->count();

        $records['recordsTotal'] = $count;
        $records['recordsFiltered'] = $count;
        $records['data'] = [];

        $countries = $countries->offset($offset)->limit($limit)->orderBy($sort_column, $sort_order);

        $countries = $countries->get();
        foreach ($countries as $country) {

            $params = [
                'checked' => ($country->is_active == 'y' ? 'checked' : ''),
                'getaction' => $country->is_active,
                'class' => '',
                'id' => $country->id,
            ];

            $records['data'][] = [
                'id' => $country->id,
                'name' => $country->name,
                'code' => $country->code,
                'phonecode' => $country->phonecode,
                'active' => view('admin.layouts.includes.switch', compact('params'))->render(),
                'action' => view('admin.layouts.includes.actions')->with(['custom_title' => 'Countries', 'id' => $country->id], $country)->render(),
                'checkbox' => view('admin.layouts.includes.checkbox')->with('id', $country->id)->render(),
            ];

        }

        return $records;
    }
    //
}

resources/views/admin/pages/general/countries/create.blade.php
@extends('admin.layouts.app')
@push('breadcrumb')
    {!! Breadcrumbs::render('countries_create') !!}
@endpush

@section('content')
<div class="container">
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon">
                    <i class="{{$icon}} text-primary"></i>
                </span>
                <h3 class="card-label text-uppercase">ADD {{ $custom_title }}</h3>
            </div>
        </div>

        <!--begin::Form-->
        <form id="frmAddCountry" method="POST" action="{{ route('admin.countries.store') }}">
            @csrf
            <div class="card-body">
                {{-- Name --}}
                <div class="form-group">
                    <label for="name">Name{!!$mend_sign!!}</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') }}" placeholder="Enter name" autocomplete="name" spellcheck="false" autocapitalize="sentences" tabindex="0" autofocus />
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong class="form-text">{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>

                {{-- code --}}
                <div class="form-group">
                    <label for="code">Code{!!$mend_sign!!}</label>
                    <input type="text" class="form-control @error('code') is-invalid @enderror" id="code" name="code" value="{{ old('code') }}" placeholder="Enter code" autocomplete="code" spellcheck="false" autocapitalize="sentences" tabindex="0" autofocus />
                    @if ($errors->has('code'))
                        <span class="help-block">
                            <strong class="form-text">{{ $errors->first('code') }}</strong>
                        </span>
                    @endif
                </div>

                {{-- phonecode --}}
                <div class="form-group">
                    <label for="phonecode">Phonecode{!!$mend_sign!!}</label>
                    <input type="text" class="form-control @error('phonecode') is-invalid @enderror" id="phonecode" name="phonecode" value="{{ old('phonecode') }}" placeholder="Enter phonecode" autocomplete="phonecode" spellcheck="false" autocapitalize="sentences" tabindex="0" autofocus />
                    @if ($errors->has('phonecode'))
                        <span class="help-block">
                            <strong class="form-text">{{ $errors->first('phonecode') }}</strong>
                        </span>
                    @endif
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary mr-2"> Add {{ $custom_title }}</button>
                <a href="{{ route('admin.countries.index') }}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
        <!--end::Form-->
    </div>
</div>
@endsection

@push('extra-js-scripts')
<script>
$(document).ready(function () {
    $("#frmAddCountry").validate({
        rules: {
            name: {
                required: true,
                not_empty: true,
                minlength: 3,
            },
            code: {
                required: true,
                not_empty: true,
                maxlength: 5,
            },
            phonecode: {
                required: true,
                not_empty: true,
                maxlength: 5,
            },
        },
        messages: {
            name: {
                required: "@lang('validation.required',['attribute'=>'name'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'name'])",
                minlength:"@lang('validation.min.string',['attribute'=>'name','min'=>3])",
            },
            code: {
                required: "@lang('validation.required',['attribute'=>'code'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'code'])",
                maxlength:"@lang('validation.max.string',['attribute'=>'code','max'=>5])",
            },
            phonecode: {
                required: "@lang('validation.required',['attribute'=>'phonecode'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'phonecode'])",
                maxlength:"@lang('validation.max.string',['attribute'=>'phonecode','max'=>5])",
            },

        },
        errorClass: 'invalid-feedback',
        errorElement: 'span',
        highlight: function (element) {
            $(element).addClass('is-invalid');
            $(element).siblings('label').addClass('text-danger'); // For Label
        },
        unhighlight: function (element) {
            $(element).removeClass('is-invalid');
            $(element).siblings('label').removeClass('text-danger'); // For Label
        },
        errorPlacement: function (error, element) {
            if (element.attr("data-error-container")) {
                error.appendTo(element.attr("data-error-container"));
            } else {
                error.insertAfter(element);
            }
        }
    });
    $('#frmAddCountry').submit(function () {
        if ($(this).valid()) {
            addOverlay();
            $("input[type=submit], input[type=button], button[type=submit]").prop("disabled", "disabled");
            return true;
        } else {
            return false;
        }
    });
});
</script>
@endpush

resources/views/admin/pages/general/countries/edit.blade.php
@extends('admin.layouts.app')
@push('breadcrumb')
    {!! Breadcrumbs::render('countries_update', $country->id) !!}
@endpush

@section('content')
<div class="container">
    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon">
                    <i class="{{$icon}} text-primary"></i>
                </span>
                <h3 class="card-label text-uppercase">Edit {{ $custom_title }}</h3>
            </div>
        </div>

        <!--begin::Form-->
        <form id="frmEditCountry" method="POST" action="{{ route('admin.countries.update', $country->id) }}" enctype="multipart/form-data">
            @csrf
            @method('put')
            <div class="card-body">

                {{--  Name --}}
                <div class="form-group">
                    <label for="name">Name{!!$mend_sign!!}</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name') != null ? old('name') : $country->name }}" placeholder="Enter name" autocomplete="name" spellcheck="false" autocapitalize="sentences" tabindex="0" autofocus />
                    @if ($errors->has('name'))
                        <span class="help-block">
                            <strong class="form-text">{{ $errors->first('name') }}</strong>
                        </span>
                    @endif
                </div>

                {{--Code --}}
                <div class="form-group">
                    <label for="code">Code {!!$mend_sign!!}</label>
                    <input type="text" class="form-control @error('code') is-invalid @enderror" id="code" name="code" value="{{ old('code') != null ? old('code') : $country->code }}" placeholder="Enter code" autocomplete="code" spellcheck="false" autocapitalize="sentences" tabindex="0" autofocus />
                    @if ($errors->has('code'))
                        <span class="help-block">
                            <strong class="form-text">{{ $errors->first('code') }}</strong>
                        </span>
                    @endif
                </div>

                {{--PhoneCode --}}
                <div class="form-group">
                    <label for="phonecode">Phonecode {!!$mend_sign!!}</label>
                    <input type="text" class="form-control @error('phonecode') is-invalid @enderror" id="phonecode" name="phonecode" value="{{ old('phonecode') != null ? old('phonecode') : $country->phonecode }}" placeholder="Enter phonecode" autocomplete="phonecode" spellcheck="false" autocapitalize="sentences" tabindex="0" autofocus />
                    @if ($errors->has('phonecode'))
                        <span class="help-block">
                            <strong class="form-text">{{ $errors->first('phonecode') }}</strong>
                        </span>
                    @endif
                </div>

            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary mr-2">Update {{ $custom_title }}</button>
                <a href="{{ route('admin.countries.index') }}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
        <!--end::Form-->
    </div>
</div>
@endsection

@push('extra-js-scripts')
<script>
$(document).ready(function () {
    $("#frmEditCountry").validate({
        rules: {
            name: {
                required: true,
                not_empty: true,
                minlength: 3,
            },
            code: {
                required: true,
                not_empty: true,
                maxlength:5,
            },
            phonecode: {
                required: true,
                not_empty: true,
                maxlength: 5,
            },
        },
        messages: {
            name: {
                required: "@lang('validation.required',['attribute'=>'name'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'name'])",
                minlength:"@lang('validation.min.string',['attribute'=>'name','min'=>3])",
            },
            code: {
                required: "@lang('validation.required',['attribute'=>'code'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'code'])",
                maxlength:"@lang('validation.max.string',['attribute'=>'code','max'=>5])",
            },
            phonecode: {
                required: "@lang('validation.required',['attribute'=>'phonecode'])",
                not_empty: "@lang('validation.not_empty',['attribute'=>'phonecode'])",
                maxlength:"@lang('validation.max.string',['attribute'=>'phonecode','max'=>5])",
            },
        },
        errorClass: 'invalid-feedback',
        errorElement: 'span',
        highlight: function (element) {
            $(element).addClass('is-invalid');
            $(element).siblings('label').addClass('text-danger'); // For Label
        },
        unhighlight: function (element) {
            $(element).removeClass('is-invalid');
            $(element).siblings('label').removeClass('text-danger');
        },
        errorPlacement: function (error, element) {
            if (element.attr("data-error-container")) {
                error.appendTo(element.attr("data-error-container"));
            } else {
                error.insertAfter(element);
            }
        }
    });
    $('#frmEditCountry').submit(function () {
        if ($(this).valid()) {
            addOverlay();
            $("input[type=submit], input[type=button], button[type=submit]").prop("disabled", "disabled");
            return true;
        } else {
            return false;
        }
    });
});
</script>
@endpush

resources/views/admin/pages/general/countries/index.blade.php
@extends('admin.layouts.app')
@push('breadcrumb')
    {!! Breadcrumbs::render('countries_list') !!}
@endpush

@push('extra-css-styles')
<link rel="stylesheet" type="text/css" href="{{ asset('assets/plugins/custom/datatables/datatables.bundle.css') }}" />
@endpush

@section('content')
<div class="container">

    <div class="card card-custom">
        <div class="card-header">
            <div class="card-title">
                <span class="card-icon">
                    <i class="{{$icon}} text-primary"></i>
                </span>
                <h3 class="card-label">{{ $custom_title }}</h3>
            </div>


            <div class="card-toolbar">
                @if (in_array('delete', $permissions))
                    <a href="{{ route('admin.countries.destroy', 0) }}" name="del_select" id="del_select" class="btn btn-sm btn-light-danger font-weight-bolder text-uppercase mr-2 delete_all_link" data-module="{{strtolower($custom_title)}}" data-route-name="{{ $routeName }}">
                        <i class="far fa-trash-alt"></i> Delete Selected
                    </a>
                @endif
                @if (in_array('add', $permissions))
                    <a href="{{ route('admin.countries.create') }}" class="btn btn-sm btn-primary font-weight-bolder text-uppercase">
                        <i class="fas fa-plus"></i>
                        Add {{ str_singular($custom_title) }}
                    </a>
                 @endif
            </div>

        </div>
        <div class="card-body">
            {{-- Datatable Start  --}}
            <table class="table table-bordered table-hover table-checkable" id="countries_table" style="margin-top: 13px !important"></table>
            {{-- Datatable End  --}}
        </div>
    </div>
</div>
@endsection

@push('extra-js-scripts')
<script src="{{ asset('assets/plugins/custom/datatables/datatables.bundle.js') }}"></script>
<script>
    $(document).ready(function() {
        // datatable
        oTable = $('#countries_table').DataTable({
            responsive: true,
            searchDelay: 500,
            processing: true,
            serverSide: true,
            ajax: {
                url: "{{ route('admin.countries.listing') }}",
                data: {
                    columnsDef: ['checkbox', 'name', 'code', 'phonecode', 'active', 'action'],
                },
            },
            columns: [{
                    data: 'checkbox'
                },
                {
                    data: 'name'
                },
                {
                    data: 'code'
                },
                {
                    data: 'phonecode'
                },
                {
                    data: 'active'
                },
                {
                    data: 'action',
                    responsivePriority: -1
                },
            ],
            columnDefs: [
                // Specify columns titles here...
                {
                    targets: 0,
                    title: "<center><input type='checkbox' class='all_select'></center>",
                    orderable: false
                },
                {
                    targets: 1,
                    title: 'Name',
                    orderable: true
                },
                {
                    targets: 2,
                    title: 'Code',
                    orderable: true
                },
                {
                    targets: 3,
                    title: 'Phonecode',
                    orderable: true
                },
                {
                    targets: 4,
                    title: 'Active',
                    orderable: false
                },
                // Action buttons
                {
                    targets: -1,
                    title: 'Action',
                    orderable: false
                },
            ],
            order: [
                [1, 'asc']
            ],
            lengthMenu: [
                [10, 20, 50, 100],
                [10, 20, 50, 100]
            ],
            pageLength: 10,
        });
    });
</script>
@endpush